import { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, Check, Database, Inbox, Plus, RefreshCw, Trash2, Upload, XCircle } from 'lucide-react';
import { get, post } from '../api';
import { useDebounced, usePolling } from '../hooks';
import { Button, Card, Checkbox, EmptyState, ErrorState, Modal, Pager, RefreshButton, SearchField, SectionHeader, Select, StatusPill, Table, Toolbar } from '../components/ui';

const SOURCES = [{ value: 'all', label: '全部来源' }, { value: 'outlook', label: 'Outlook' }, { value: 'generic_api', label: '通用 API' }, { value: 'cloudflare_domain', label: 'Cloudflare 域名' }];
const STATUSES = [{ value: '', label: '全部状态' }, { value: 'available', label: '可用' }, { value: 'used', label: '已使用' }, { value: 'failed', label: '失败' }, { value: 'disabled', label: '已禁用' }];

export default function MailboxPage({ notify }) {
  const [rows, setRows] = useState([]); const [total, setTotal] = useState(0); const [source, setSource] = useState('all'); const [status, setStatus] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [size, setSize] = useState(20); const [selected, setSelected] = useState(new Set()); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [importOpen, setImportOpen] = useState(false); const [importSource, setImportSource] = useState('outlook'); const [importText, setImportText] = useState(''); const [asRegistered, setAsRegistered] = useState(false); const [importing, setImporting] = useState(false);
  const debouncedQuery = useDebounced(query);
  const load = useCallback(async () => { try { const response = await get('/api/outlook', { source, status, q: debouncedQuery, paged: 1, page, page_size: size }); setRows(response.items || []); setTotal(Number(response.total || 0)); setError(''); setSelected((current) => new Set([...current].filter((key) => (response.items || []).some((row) => `${row.source || source}|${row.email}` === key)))); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }, [source, status, debouncedQuery, page, size]);
  const { refresh, running } = usePolling(load, 5000, true);
  useEffect(() => setPage(1), [source, status, debouncedQuery, size]);
  const keys = useMemo(() => [...selected], [selected]);
  const keyFor = (row) => `${row.source || source}|${row.email}`;
  const toggleAll = (checked) => setSelected(checked ? new Set(rows.map(keyFor)) : new Set());
  const toggle = (key, checked) => setSelected((current) => { const next = new Set(current); checked ? next.add(key) : next.delete(key); return next; });
  const selectedItems = rows.filter((row) => selected.has(keyFor(row))).map((row) => ({ email: row.email, source: row.source || source }));
  async function bulkStatus(nextStatus) { if (!keys.length) return notify('请先选择邮箱', 'warning'); try { await post('/api/outlook/status-bulk', { items: selectedItems, status: nextStatus, source }); notify(`已更新 ${selectedItems.length} 个邮箱`, 'success'); await load(); } catch (error) { notify(error.message, 'error'); } }
  async function bulkDelete() { if (!keys.length) return notify('请先选择邮箱', 'warning'); if (!window.confirm(`确定删除选中的 ${selectedItems.length} 个邮箱吗？此操作不可恢复。`)) return; try { await post('/api/outlook/delete-bulk', { items: selectedItems, source }); notify('已删除选中邮箱', 'success'); setSelected(new Set()); await load(); } catch (error) { notify(error.message, 'error'); } }
  async function doImport() { if (!importText.trim()) return notify('请粘贴导入内容', 'warning'); setImporting(true); try { const response = await post('/api/outlook/import', { text: importText, source: importSource, as_registered: asRegistered }); notify(`解析 ${response.parsed} 条，导入 ${response.inserted} 条`, 'success'); setImportText(''); setImportOpen(false); await load(); } catch (error) { notify(error.message, 'error'); } finally { setImporting(false); } }

  return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow"><Inbox size={14} /> MAILBOX POOL</div><h2>邮箱池</h2><p>管理注册素材的来源、可用状态和批量导入。</p></div><Button icon={Upload} variant="primary" onClick={() => setImportOpen(true)}>导入邮箱素材</Button></div>
    <Card className="table-card"><SectionHeader title="邮箱素材" description="状态更新会写回本地池，删除操作不可恢复。" actions={<div className="section-actions"><Button icon={Check} size="sm" disabled={!keys.length} onClick={() => bulkStatus('available')}>标记可用</Button><Button icon={Archive} size="sm" disabled={!keys.length} onClick={() => bulkStatus('used')}>标记已用</Button><Button icon={XCircle} size="sm" disabled={!keys.length} onClick={() => bulkStatus('failed')}>标记失败</Button><Button icon={Trash2} variant="danger" size="sm" disabled={!keys.length} onClick={bulkDelete}>删除</Button></div>} />
      <Toolbar className="filter-toolbar"><SearchField value={query} onChange={setQuery} placeholder="搜索邮箱、备注或来源…" /><Select value={source} onChange={setSource} options={SOURCES} /><Select value={status} onChange={setStatus} options={STATUSES} /><span className="selection-note">已选 {keys.length}</span><RefreshButton onClick={refresh} loading={running} /></Toolbar>{error ? <ErrorState message={error} onRetry={load} /> : null}
      <Table><thead><tr><th className="check-col"><Checkbox checked={rows.length > 0 && rows.every((row) => selected.has(keyFor(row)))} onChange={toggleAll} /></th><th>邮箱</th><th>来源</th><th>状态</th><th>备注</th><th>导入时间</th><th className="actions-col">操作</th></tr></thead><tbody>{loading ? <tr><td colSpan="7"><div className="table-loading"><span className="loading-bar" /><span className="loading-bar" /><span className="loading-bar" /></div></td></tr> : rows.length === 0 ? <tr><td colSpan="7"><EmptyState title="邮箱池为空" description="导入 Outlook 或通用 API 素材后，它们会在这里排队。" action={<Button icon={Plus} size="sm" onClick={() => setImportOpen(true)}>导入第一批</Button>} /></td></tr> : rows.map((row) => <tr key={keyFor(row)}><td><Checkbox checked={selected.has(keyFor(row))} onChange={(checked) => toggle(keyFor(row), checked)} /></td><td><strong>{row.email || '—'}</strong><small className="table-sub">{row.copy_line || ''}</small></td><td><span className="source-tag"><Database size={13} />{row.source === 'generic_api' ? '通用 API' : row.source === 'cloudflare_domain' ? 'Cloudflare' : 'Outlook'}</span></td><td><StatusPill value={row.status} /></td><td className="truncate" title={row.note || ''}>{row.note || '—'}</td><td>{row.imported_at || row.created_at || '—'}</td><td><div className="row-actions"><Button icon={Check} size="sm" onClick={() => post('/api/outlook/status', { email: row.email, source: row.source, status: 'available' }).then(() => { notify('已标记可用', 'success'); load(); }).catch((error) => notify(error.message, 'error'))}>可用</Button><Button icon={Trash2} variant="danger" size="sm" onClick={() => { if (!window.confirm('确定删除这个邮箱吗？此操作不可恢复。')) return; post('/api/outlook/delete', { email: row.email, source: row.source }).then(() => { notify('邮箱已删除', 'success'); load(); }).catch((error) => notify(error.message, 'error')); }}>删除</Button></div></td></tr>)}</tbody></Table><Pager page={page} pageSize={size} total={total} onPageChange={setPage} onPageSizeChange={(value) => { setSize(value); setPage(1); }} /></Card>
    <Modal open={importOpen} title="导入邮箱素材" onClose={() => setImportOpen(false)} wide footer={<><Button onClick={() => setImportOpen(false)}>取消</Button><Button variant="primary" icon={Upload} onClick={doImport} loading={importing}>开始导入</Button></>}><div className="form-grid"><Select label="素材类型" value={importSource} onChange={setImportSource} options={[{ value: 'outlook', label: 'Outlook：邮箱----密码----clientId----refreshToken' }, { value: 'generic_api', label: '通用 API：邮箱----取码地址' }]} /><label className="checkbox form-toggle"><input type="checkbox" checked={asRegistered} onChange={(event) => setAsRegistered(event.target.checked)} /><span>同时写入已注册账号</span></label></div><label className="field-label">粘贴内容<textarea rows="12" value={importText} onChange={(event) => setImportText(event.target.value)} placeholder={importSource === 'outlook' ? 'email----password----clientId----refreshToken' : '邮箱---接码 URL'} spellCheck="false" /></label><p className="field-help">通用 API 按内容识别邮箱和 HTTP 接码地址；分隔符在「配置 → 邮箱 / OTP」中设置。</p></Modal>
  </div>;
}
